### ISSUE TITLE
Installing via pip install does not bring in all requriements

### ISSUE THREAD

**Issue by michou** [tg123/bottle-mysql#10]
Installing this via `pip install bottle-mysql` does not bring in all necessary requirements, mainly `MySQLdb`. In turn, trying to run any code that uses a DB, will yield this error:

```
Traceback (most recent call last):
  File "application.py", line 2, in <module>
    import bottle_mysql
  File "/Users/michou/git/mock/lib/python2.7/site-packages/bottle_mysql.py", line 40, in <module>
    import MySQLdb
ImportError: No module named MySQLdb
```

**Comment by tg123** [comment]
can you try to install mysqlclient via
```pip install mysqlclient ```?

_note_: mysqlclient require python c headers and relate build tools  

please refer to https://github.com/PyMySQL/mysqlclient-python/issues/14
